env: "prod"

pg_config:
  host: "158.160.26.238"
  port: 5432
  user: "todo_list"
  password: "pg"
  db_name: "todo_list"
  migrations_dir: "/app/migrations"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s