env: "prod"

pg_config:
  host: "localhost"
  port: 5432
  user: "timofey"
  password: "879351"
  db_name: "todolist-db"
  migrations_dir: "/Users/timofey/GolandProjects/todo_list_service/pkg/storage/postgres/migrations"

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
  session:
    secret_key: "secret_key"
    secure: false
    max_age: 604800