env: "prod"

pg_config:
  host:
  port:
  user:
  password:
  db_name:
  migrations_dir:

http_server:
  host: "0.0.0.0"
  port: 80
  timeout: 4s
  idle_timeout: 30s
  session:
    secret_key: "secret_key"
    secure: false
    max_age: 604800