name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  PROJECT_PATH: ${{ github.workspace }}
  TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
  TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
  PROD_HOST: ${{ vars.PROD_HOST }}
  PROD_USERNAME: ${{ vars.PROD_USERNAME }}
  APP_IMAGE: "ghcr.io/ypodlesov/todo_list_service/todo-list-image:latest"

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd $PROJECT_PATH/deployment/app_image && make docker-push

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Auth
      run: ssh $PROD_USERNAME@$PROD_HOST "echo $GITHUB_TOKEN | docker login ghcr.io -u ypodlesov --password-stdin"

    - name: Pull image
      run: ssh $PROD_USERNAME@$PROD_HOST "docker pull $APP_IMAGE"

    - name: Stop running container with the same tag
      run: |
        ssh $PROD_USERNAME@$PROD_HOST "docker ps --format '{{.ID}} {{.Image}}' | grep $APP_IMAGE | awk '{print $1}' | xargs docker stop" || true

    - name: Run image
      run: ssh $PROD_USERNAME@$PROD_HOST "docker run -d $APP_IMAGE"